import AddPersonListAction from "./Person/Manage"
import Addresses from "./Address/List"
import AddressForm from "./Address/Form"
import AddressManage from "./Address/Manage"
import BankAccountManage from "./BankAccount/Manage"
import BankAccounts from "./BankAccount/List"
import ContactHeaders from "./Contact/Headers"
import ContactRow from "./Contact/Row"
import ContactsInputs from "./Contact/Inputs"
import EditPerson from "./Person/Edit"
import Emails from "./Email/List"
import JuridicalPersonEditForm from "./JuridicalPerson/Edit"
import JuridicalPersonField from "./JuridicalPerson/Field"
import JuridicalPersonForm from "./JuridicalPerson/Form"
import JuridicalPersonInputs from "./JuridicalPerson/Inputs"
import JuridicalPersons from "./JuridicalPerson/List"
import ManageSocialProfiles from "./SocialProfile/Manage"
import NaturalOrJuridical from "./Person/NaturalOrJuridical"
import NaturalPersonEditForm from "./NaturalPerson/Edit"
import NaturalPersonField from "./NaturalPerson/Field"
import NaturalPersonForm from "./NaturalPerson/Form"
import NaturalPersonInputs from "./NaturalPerson/Inputs"
import NaturalPersons from "./NaturalPerson/List"
import PersonField from "./Person/Field"
import PersonFilter from "./Person/Filter"
import PersonForm from "./Person/Form"
import PersonImage from "./Person/Image"
import PersonInfo from "./Profile/PersonInfo"
import PersonNameTd from "./Person/NameTd"
import PersonProperty from "./Person/Property"
import Persons from "./Person/List"
import PersonTypeFilter from "./Person/PersonTypeFilter"
import PhoneManage from "./Phone/Manage"
import Phones from "./Phone/List"
import Relations from "./Relation/List"
import SocialNetworks from "./SocialNetwork/List"
import SocialProfiles from "./SocialProfile/List"
import useDefaultPersonType from "./Hooks/UseDefaultPersonType"

export { AddPersonListAction }
export { Addresses }
export { AddressForm }
export { AddressManage }
export { BankAccountManage }
export { BankAccounts }
export { ContactHeaders }
export { ContactRow }
export { ContactsInputs }
export { EditPerson }
export { Emails }
export { JuridicalPersonEditForm }
export { JuridicalPersonField }
export { JuridicalPersonForm }
export { JuridicalPersonInputs }
export { JuridicalPersons }
export { ManageSocialProfiles }
export { NaturalOrJuridical }
export { NaturalPersonEditForm }
export { NaturalPersonField }
export { NaturalPersonForm }
export { NaturalPersonInputs }
export { NaturalPersons }
export { PersonField }
export { PersonFilter }
export { PersonForm }
export { PersonImage }
export { PersonInfo }
export { PersonNameTd }
export { PersonProperty }
export { Persons }
export { PersonTypeFilter }
export { PhoneManage }
export { Phones }
export { Relations }
export { SocialNetworks }
export { SocialProfiles }
export { useDefaultPersonType }
