import defaultTheme from "tailwindcss/defaultTheme"
import typography from "@tailwindcss/typography"
import scrollbar from "tailwind-scrollbar"
import plugin from "tailwindcss/plugin"

const config = {
    darkMode: "selector",
    content: [
        "./index.html",
        "./src/**/*.{js,jsx}",
    ],
    safelist: [
        "sm:col-span-1",
        "sm:col-span-2",
        "md:col-span-1",
        "md:col-span-2",
        "md:col-span-3",
        "md:col-span-4",
        "lg:col-span-1",
        "lg:col-span-2",
        "lg:col-span-3",
        "lg:col-span-4",
        "lg:col-span-5",
        "lg:col-span-6",
        "xl:col-span-1",
        "xl:col-span-2",
        "xl:col-span-3",
        "xl:col-span-4",
        "xl:col-span-5",
        "xl:col-span-6",
        "xl:col-span-7",
        "xl:col-span-8",
        "2xl:col-span-1",
        "2xl:col-span-2",
        "2xl:col-span-3",
        "2xl:col-span-4",
        "2xl:col-span-5",
        "2xl:col-span-6",
        "2xl:col-span-7",
        "2xl:col-span-8",
        "2xl:col-span-9",
        "2xl:col-span-10",
        "2xl:col-span-11",
        "2xl:col-span-12",
        "sm:row-span-1",
        "sm:row-span-2",
        "md:row-span-1",
        "md:row-span-2",
        "md:row-span-3",
        "md:row-span-4",
        "lg:row-span-1",
        "lg:row-span-2",
        "lg:row-span-3",
        "lg:row-span-4",
        "lg:row-span-5",
        "lg:row-span-6",
        "xl:row-span-1",
        "xl:row-span-2",
        "xl:row-span-3",
        "xl:row-span-4",
        "xl:row-span-5",
        "xl:row-span-6",
        "xl:row-span-7",
        "xl:row-span-8",
        "2xl:row-span-1",
        "2xl:row-span-2",
        "2xl:row-span-3",
        "2xl:row-span-4",
        "2xl:row-span-5",
        "2xl:row-span-6",
        "2xl:row-span-7",
        "2xl:row-span-8",
        "2xl:row-span-9",
        "2xl:row-span-10",
        "2xl:row-span-11",
        "2xl:row-span-12",
    ],
    theme: {
        screens: {
            "xs": "360px",
            ...defaultTheme.screens,
        },
        extend: {
        },
    },
    plugins: [
        scrollbar,
        typography,
    ],
    important: true
}

export default config
