import useAdvertisementsBreadcrumb from "./Advertisements/Admin/Hooks/UseBreadcrumb.jsx"
export { useAdvertisementsBreadcrumb }
import useBlogBreadcrumb from "./Blog/Admin/Hooks/UseBreadcrumb.jsx"
export { useBlogBreadcrumb }
import useBrandsBreadcrumb from "./Brands/Admin/Hooks/UseBreadcrumb.jsx"
export { useBrandsBreadcrumb }
import useCoursesBreadcrumb from "./Courses/Admin/Hooks/UseBreadcrumb.jsx"
export { useCoursesBreadcrumb }
import useFlowsBreadcrumb from "./Flows/Admin/Hooks/UseBreadcrumb.jsx"
export { useFlowsBreadcrumb }
import useGeoBreadcrumb from "./Geo/Admin/Hooks/UseBreadcrumb.jsx"
export { useGeoBreadcrumb }
import useGlossaryBreadcrumb from "./Glossary/Admin/Hooks/UseBreadcrumb.jsx"
export { useGlossaryBreadcrumb }
import useProductsBreadcrumb from "./Products/Common/Hooks/UseBreadcrumb.jsx"
export { useProductsBreadcrumb }
import useProjectsBreadcrumb from "./Projects/Admin/Hooks/UseBreadcrumb.jsx"
export { useProjectsBreadcrumb }
import useStateMachinesBreadcrumb from "./StateMachines/Admin/Hooks/UseBreadcrumb.jsx"
export { useStateMachinesBreadcrumb }
import useTasksBreadcrumb from "./Tasks/Admin/Hooks/UseBreadcrumb.jsx"
export { useTasksBreadcrumb }
import useVlogBreadcrumb from "./Vlog/Admin/Hooks/UseBreadcrumb.jsx"
export { useVlogBreadcrumb }
